# frozen_string_literal: true

# This file is auto-generated by GraphqlResource generator
# It may be overwritten by the generator when the resource is updated

module GraphqlResource::Customer::Queries
  WhereTemplate = <<~GRAPHQL.squish
    query(first: Int, after: String, last: Int, before: String, reverse: Boolean, sortKey: CustomerSortKeys, query: String) {
      customers(first: $first, after: $after, last: $last, before: $before, reverse: $reverse, sortKey: $sortKey, query: $query) {
        %<fragment>s
      }
    }
  GRAPHQL
end
