# frozen_string_literal: true

# This file is auto-generated by GraphqlResource generator
# It may be overwritten by the generator when the resource is updated

module GraphqlResource::Customer::Queries
    CustomerTemplate = <<~GRAPHQL.squish
      query(id: ID!) {
        customer(id: $id) {
          %<fragment>s
        }
      }
    GRAPHQL
  end
end
