# frozen_string_literal: true

# This file is auto-generated by GraphqlResource generator
# It may be overwritten by the generator when the resource is updated

module Customer::Fragments
  Default = GraphqlResource::Client.parse <<~GRAPHQL.squish
    fragment on Customer {
      acceptsMarketing
      acceptsMarketingUpdatedAt
      addresses
      amountSpent
      canDelete
      companyContactProfiles
      createdAt
      defaultAddress
      displayName
      email
      emailMarketingConsent
      firstName
      hasTimelineComment
      id
      image
      lastName
      lastOrder
      legacyResourceId
      lifetimeDuration
      locale
      market
      marketingOptInLevel
      mergeable
      metafield
      multipassIdentifier
      note
      numberOfOrders
      phone
      privateMetafield
      productSubscriberStatus
      smsMarketingConsent
      state
      statistics
      tags
      taxExempt
      taxExemptions
      unsubscribeUrl
      updatedAt
      validEmailAddress
      verifiedEmail
    }
  GRAPHQL
end
